services:
  - type: web
    name: blueberry-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_FORCE_DEPLOY
        value: "true"
