services:
  - type: web
    name: blueberry-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blueberry-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: blueberry-db
    databaseName: blueberry
    user: blueberry
